#!/usr/bin/with-contenv bash
# shellcheck shell=bash

function 020_mkdir {

	if [ ! -d /data ]; then
		mkdir /data
	fi

	if [ ! -d ${SMANGA_CONFIG} ]; then
		mkdir -p ${SMANGA_CONFIG}
	fi

	if [ ! -d ${SMANGA_COMPRESS} ]; then
		mkdir -p ${SMANGA_COMPRESS}
	fi

	if [ ! -d ${SMANGA_POSTER} ]; then
		mkdir -p ${SMANGA_POSTER}
	fi

	if [ ! -d ${SMANGA_BOOKMARK} ]; then
		mkdir -p ${SMANGA_BOOKMARK}
	fi

}

020_mkdir 2>&1 | sed "s#^#cont-init: info: $(realpath $0): &#g"