#!/usr/bin/with-contenv bash
# shellcheck shell=bash

function 030_config {

	if [ ! -f ${SMANGA_CONFIG_INI} ]; then
		cp /app/config/config.ini ${SMANGA_CONFIG_INI}
	fi

}

030_config 2>&1 | sed "s#^#cont-init: info: $(realpath $0): &#g"