#!/usr/bin/with-contenv bash
# shellcheck shell=bash

function 030_config {

	if [ ! -f /config/config.ini ]; then
		cp /app/config/config.ini /config/config.ini
	fi

	if [ -f /config/sql.ini ]; then
		echo -e "The sql.ini setting is obsolete!\nPlease manually delete the sql.ini configuration file and reconfigure the config.ini configuration file."
	fi

}

030_config 2>&1 | sed "s#^#cont-init: info: $(realpath $0): &#g"