export interface GlobalData {
    bookmarkList: any[],
    chapterList: any[],
    imgPathList: string[],
    chapterIndex: number,
    chapterId: number,
    chapterName: string,
    chapterPath: string,
    chapterType: string,
    browseType: string,
    chapterCover: string,
    mediaId: number,
    mangaId: number,
    mangaName: string,
    mangaCover: string,
    page: number,
    doublePage: number,
    pageImage: string,
    direction: string,
    removeFirst: string,
    loadedImages: number,
}
