#!/usr/bin/with-contenv bash

function 100_mysql {
if [ ! -d /var/lib/mysql/smanga ]; then
    cp -r /var/lib/mysql_bak/* /var/lib/mysql
fi

chown smanga:smanga -R /var/lib/mysql /run/mysqld
}

100_mysql 2>&1 | sed "s#^#cont-init: info: $(realpath $0): \1#g"