#!/usr/bin/with-contenv bash
# shellcheck shell=bash

function 120_mysql_fixuser {

    echo "Change mysql owner to user smanga..."
    echo "It may take a while"
    if [ -d /var/lib/mysql ]; then
        chown smanga:smanga -R /data/db /var/lib/mysql
    else
        chown smanga:smanga -R /data/db
    fi

}

120_mysql_fixuser 2>&1 | sed "s#^#cont-init: info: $(realpath $0): &#g"