#!/usr/bin/with-contenv bash
# shellcheck shell=bash

function 200_app_init {

    if [ -f ${SMANGA_CONFIG}/install.lock ]; then
        if [ ! -f /app/php/public/version ]; then

            # 启动mysql
            /usr/bin/mysqld_safe --datadir='/data/db' &
            echo "Wait mysql start"
            while ! mysqladmin ping -h"localhost" --silent; do
                sleep 1
            done

            cd /app/php/public
            s6-setuidgid smanga php7 /app/php/public/init.php
            echo

            # 关闭mysql
            mysqladmin shutdown
            echo "Wait mysql stop"
            while mysqladmin ping -h"localhost" --silent; do
                sleep 1
            done
            echo "Mysql stopped"
        
        fi
    fi

}

200_app_init 2>&1 | sed "s#^#cont-init: info: $(realpath $0): &#g"
