#!/usr/bin/with-contenv bash
# shellcheck shell=bash

function crond {

    echo -e "0 3 * * * find /data/logs -type f -name '*.log' -exec truncate -s 0 {} \;" >> /tmp/crontab.list

    echo "Set crontab to system..."
    crontab /tmp/crontab.list
    echo "Current crontab is:"
    crontab -l
    rm -f /tmp/crontab.list

}

#crond