#!/usr/bin/with-contenv bash
# shellcheck shell=bash

function 030_config {

	# 旧配置情况下肯定会存在config.ini配置文件，所以这部不用管。
	if [ ! -f ${SMANGA_CONFIG_INI} ]; then
		cp /app/config/config.ini ${SMANGA_CONFIG_INI}
		echo "Create ${SMANGA_CONFIG_INI}"
	fi

}

030_config 2>&1 | sed "s#^#cont-init: info: $(realpath $0): &#g"