#!/usr/bin/with-contenv bash
# shellcheck shell=bash

function 080_crond {

    echo -e "0 3 * * * find /logs -type f -name '*.log' -exec truncate -s 0 {} \;" >> /tmp/crontab.list

    echo "Set crontab to system..."
    crontab /tmp/crontab.list
    echo "Current crontab is:"
    crontab -l
    rm -f /tmp/crontab.list

}

080_crond 2>&1 | sed "s#^#cont-init: info: $(realpath $0): &#g"