#!/usr/bin/with-contenv bash
# shellcheck shell=bash

function 090_fixuser {

    groupmod -o -g "${PGID}" smanga
    usermod -o -u "${PUID}" smanga

    # smanga app
    chown smanga:smanga -R /app

    if [ -d /config ]; then
        chown smanga:smanga -R \
            ${SMANGA_CONFIG} \
            /config
    else
        chown smanga:smanga -R ${SMANGA_CONFIG}
    fi

    if [ -d /compress ]; then
        chown smanga:smanga \
            ${SMANGA_COMPRESS} \
            /compress
    else
        chown smanga:smanga ${SMANGA_COMPRESS}
    fi

    if [ -d /poster ]; then
        chown smanga:smanga \
            ${SMANGA_POSTER} \
            /poster \
            ${SMANGA_BOOKMARK} \
            /poster/bookmark
    else
        chown smanga:smanga \
            ${SMANGA_POSTER} \
            ${SMANGA_BOOKMARK}
    fi

    # logs
    chown smanga:smanga -R /logs
    # Nginx
    chown smanga:smanga -R /var/lib/nginx /run/nginx /var/log/nginx
    # PHP
    chown smanga:smanga -R /run/php

}
echo -e "Change owner to user smanga...\nIt may take a while" | sed "s#^#cont-init: info: $(realpath $0): &#g"

090_fixuser 2>&1 | sed "s#^#cont-init: info: $(realpath $0): &#g"
