#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [ ! -d /data ]; then
	mkdir /data
	echo "Create /data"
fi

if [ ! -d /data/logs ]; then
	mkdir /data/logs
	echo "Create /data/logs"
fi

if [ -d /config ]; then
	if [ "${SMANGA_CONFIG}" != /config ]; then
		if [[ $(readlink -f /data/config 2>/dev/null) != /config ]]; then
			rm -rf /data/config
			ln -sf /config /data/config
			echo "Soft link /config --> /data/config"
		fi
	fi
else
	if [ ! -d ${SMANGA_CONFIG} ]; then
		mkdir -p ${SMANGA_CONFIG}
		echo "Create ${SMANGA_CONFIG}"
	fi
fi

if [ -d /compress ]; then
	if [ "${SMANGA_COMPRESS}" != /compress ]; then
		if [[ $(readlink -f /data/compress 2>/dev/null) != /compress ]]; then
			rm -rf /data/compress
			ln -sf /compress /data/compress
			echo "Soft link /compress --> /data/compress"
		fi
	fi
else
	if [ ! -d ${SMANGA_COMPRESS} ]; then
		mkdir -p ${SMANGA_COMPRESS}
		echo "Create ${SMANGA_COMPRESS}"
	fi
fi

if [ -d /poster ]; then
	if [ "${SMANGA_POSTER}" != /poster ]; then
		if [[ $(readlink -f /data/poster 2>/dev/null) != /poster ]]; then
			rm -rf /data/poster
			ln -sf /poster /data/poster
			echo "Soft link /poster --> /data/poster"
		fi
	else
		if [ ! -d ${SMANGA_BOOKMARK} ]; then
			mkdir -p ${SMANGA_BOOKMARK}
			echo "Create ${SMANGA_BOOKMARK}"
		fi
	fi
else
	if [ ! -d ${SMANGA_POSTER} ]; then
		mkdir -p ${SMANGA_POSTER}
		echo "Create ${SMANGA_POSTER}"
	fi

	if [ ! -d ${SMANGA_BOOKMARK} ]; then
		mkdir -p ${SMANGA_BOOKMARK}
		echo "Create ${SMANGA_BOOKMARK}"
	fi
fi
