/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Bar: typeof import('./components/charts/bar.vue')['default']
    BrowsePager: typeof import('./components/browse-pager.vue')['default']
    Chapter: typeof import('./components/chapter.vue')['default']
    CoverUpload: typeof import('./components/cover-upload.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    Line: typeof import('./components/charts/line.vue')['default']
    List: typeof import('./components/charts/list.vue')['default']
    ListSkeleton: typeof import('./components/list-skeleton.vue')['default']
    Manga: typeof import('./components/manga.vue')['default']
    MediaPager: typeof import('./components/media-pager.vue')['default']
    Notice: typeof import('./components/notice.vue')['default']
    Pie: typeof import('./components/charts/pie.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Seat: typeof import('./components/seat.vue')['default']
    Share: typeof import('./components/share.vue')['default']
    TablePager: typeof import('./components/table-pager.vue')['default']
  }
}
