#!/usr/bin/with-contenv bash
# shellcheck shell=bash

function 020_mkdir {
if [ ! -d /compress ]; then
	mkdir /compress
fi

if [ ! -d /poster ]; then
	mkdir /poster
fi

if [ ! -d /config ]; then
	mkdir /config
fi

if [ ! -d /sql ]; then
	mkdir /sql
fi

}

020_mkdir 2>&1 | sed "s#^#[cont-init.d] info: $(realpath $0): &#g"