#!/usr/bin/with-contenv bash
# shellcheck shell=bash

function 120_mysql_fixuser {

    if [ -d /var/lib/mysql ]; then
        chown smanga:smanga -R /data/db /var/lib/mysql
    else
        chown smanga:smanga -R /data/db
    fi

}

120_mysql_fixuser 2>&1 | sed "s#^#cont-init: info: $(realpath $0): &#g"