name: Build Smanga Beta Docker

on:
    workflow_dispatch:
    push:
      branches:
        - dev
      paths:
        - package.json

jobs:
  build:
    name: Build Smanga Docker
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      
      - 
        name: Set Version
        id: set-version
        run: |
          SMANGA_VERSION=$(jq -r '.version' package.json)
          echo "version=${SMANGA_VERSION}" >> $GITHUB_OUTPUT

      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/smanga
          tags: |
            type=raw,value=nosql-${{ steps.set-version.outputs.version }}
            type=raw,value=nosql-beta

      -
        name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      -
        name: Build Web
        run: |
          npm set strict-ssl false
          npm install
          npm run build-docker

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v3
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile
          platforms: |
            linux/amd64
            linux/arm64/v8
          push: true
          build-args: |
            SMANGA_VERSION=${{ steps.set-version.outputs.version }}
            SMANGA_BASE_NAME=${{ secrets.DOCKER_USERNAME }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


  build_mysql:
    needs: [build]
    name: Build Smanga Mysql Docker
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@master
      
      - 
        name: Set Version
        id: set-version
        run: |
          SMANGA_VERSION=$(jq -r '.version' package.json)
          echo "version=${SMANGA_VERSION}" >> $GITHUB_OUTPUT

      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/smanga
          tags: |
            type=raw,value=${{ steps.set-version.outputs.version }}
            type=raw,value=beta

      - 
        name: Set Up QEMU
        uses: docker/setup-qemu-action@v3

      - 
        name: Set Up Buildx
        uses: docker/setup-buildx-action@v3
        
      - 
        name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - 
        name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/mysql.Dockerfile
          platforms: |
            linux/amd64
            linux/arm64/v8
          push: true
          build-args: |
            SMANGA_VERSION=${{ steps.set-version.outputs.version }}
            SMANGA_BASE_NAME=${{ secrets.DOCKER_USERNAME }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
